Bump org.projectlombok:lombok from 1.18.30 to 1.18.32 in /leaders (#96)
Bumps
[org.projectlombok:lombok](https://github.com/projectlombok/lombok) from
1.18.30 to 1.18.32.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/projectlombok/lombok/blob/master/doc/changelog.markdown">org.projectlombok:lombok's
changelog</a>.</em></p>
<blockquote>
<h3>v1.18.32 (March 20th, 2024)</h3>
<ul>
<li>PLATFORM: Initial JDK22 support added.</li>
<li>PLAFTORM Added support for Eclipse 2024-03. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3620">#3620</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3620">projectlombok/lombok#3620</a>).</li>
<li>PLATFORM: Added support for recent versions of eclipse (released Q4
2023 or later or so) which would cause failures in the eclipse logs such
as <code>java.lang.NoSuchMethodError: 'java.lang.StringBuffer
org.eclipse.jdt…</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3564">#3564</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3564">projectlombok/lombok#3564</a>).</li>
<li>FEATURE: <code>@Locked</code> has been introduced. Like
<code>@Synchronized</code> but with
<code>java.util.concurrent.locks</code> locks instead of the
<code>synchronized</code> primitive. Thanks, Pim van der Loos for the
PR! [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3506">#3506</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3506">projectlombok/lombok#3506</a>).</li>
<li>NECROMANCY: Inlining a generated getter in eclipse would result in
eclipse incorrectly replacing calls with <code>@Getter</code> instead of
the actual field's name. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/562">#562</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/562">projectlombok/lombok#562</a>).
This issue is almost old enough to drink. Points for dedication go to
Rawi for fixing this one.</li>
<li>BUGFIX: When <code>@SuperBuilder</code> was used on a type with an
annotated generic type, it would error <code>wrong number of type
arguments</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3592">#3592</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3592">projectlombok/lombok#3592</a>).</li>
<li>BUGFIX: It was possible to create an infinite build loop using
<code>@ExtensionMethod</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3225">#3225</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3225">projectlombok/lombok#3225</a>).</li>
<li>BUGFIX: Using <code>@Getter(lazy=true)</code> would fail if the
expression contained a variable called <code>value</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/2917">#2917</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/2917">projectlombok/lombok#2917</a>).</li>
<li>BUGFIX: Many lombok features wouldn't work properly on records
contained within an outer type unless you explicitly marked it
<code>static</code>. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3497">#3497</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3497">projectlombok/lombok#3497</a>)
[Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3559">#3559</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3559">projectlombok/lombok#3559</a>).</li>
<li>BUGFIX: Eclipse projects using the
<code>com.pro-crafting.tools:jasperreports-plugin</code> will now
compile.</li>
<li>BUGFIX: <code>@FieldNameConstants</code> now works when generated
fields are involved. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3529">#3529</a>](<a
href="https://redirect.github.com/projectlombok/lombok/issues/3529">projectlombok/lombok#3529</a>).</li>
<li>IMPROBABLE BREAKING CHANGE: For JSpecify, the package name changed
from <code>org.jspecify.nullness</code> to
<code>org.jspecify.annotations</code>, which might lead to a different
null analysis. [Issue <a
href="https://redirect.github.com/projectlombok/lombok/issues/3608">#3608</a>](<a
href="https://redirect.github.com/projectlombok/lombok/pull/3608">projectlombok/lombok#3608</a>).</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/projectlombok/lombok/commit/2618848385de2ec4b79677e01eb8045714de1110"><code>2618848</code></a>
[release] pre-release version bump</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/5719fde58e1faf04d436e85c86ae50acf8ede272"><code>5719fde</code></a>
Update changelog in preparation for the upcoming release</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/1b713add959430ee22145050a638f01102d158c5"><code>1b713ad</code></a>
Add eclipse 2024-03 as test target</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/521be03be45887ea738e005b5f317e04ca6196d2"><code>521be03</code></a>
Remove unused string literal code</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/3b20b70363fe85f354934fcfb47fdcfd0701a31e"><code>3b20b70</code></a>
Support <a
href="https://github.com/Delegate"><code>@​Delegate</code></a> in
eclipse 2024-03</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/98cdf67ed6846580e8e4e77391fd48f3293603f6"><code>98cdf67</code></a>
Javadoc support for eclipse 2024-03</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/e4824cbe1405fd665f289f7178d6149a8fcdd7b5"><code>e4824cb</code></a>
Fix Javadoc in Eclipse</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/c93400d9f44b1e06aa3763c4a2818e43b70f3630"><code>c93400d</code></a>
[fixes <a
href="https://redirect.github.com/projectlombok/lombok/issues/2917">#2917</a>]
Use $value instead of value in lazy getter</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/23307eb8d137d7e4a3f645552135ab7354ca1e6e"><code>23307eb</code></a>
[jdk22] Adds support for unnamed variables (JEP 456)</li>
<li><a
href="https://github.com/projectlombok/lombok/commit/a54ec7005ed253d480621f042d923f3353e6a1d0"><code>a54ec70</code></a>
Document using jdk22 GA</li>
<li>Additional commits viewable in <a
href="https://github.com/projectlombok/lombok/compare/v1.18.30...v1.18.32">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.projectlombok:lombok&package-manager=gradle&previous-version=1.18.30&new-version=1.18.32)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>