Bump org.springframework.boot from 3.2.5 to 3.3.0 in /workers (#188)
Bumps
[org.springframework.boot](https://github.com/spring-projects/spring-boot)
from 3.2.5 to 3.3.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/spring-projects/spring-boot/releases">org.springframework.boot's
releases</a>.</em></p>
<blockquote>
<h2>v3.3.0-RC1</h2>
<h2>:star: New Features</h2>
<ul>
<li>Add configuration key spring.rabbitmq.template.allowed-list-patterns
<a
href="https://redirect.github.com/spring-projects/spring-boot/pull/40421">#40421</a></li>
<li>Add spring.graphql.websocket.keep-alive property <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40320">#40320</a></li>
<li>Add Spring Pulsar transaction support <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/40189">#40189</a></li>
<li>Make it harder to misconfigure logging.threshold.console in yaml <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40124">#40124</a></li>
<li>Make configuration properties for Pulsar failover more concise <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40077">#40077</a></li>
<li>Add support for Prometheus Client 1.x and simpleclient <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/40023">#40023</a></li>
<li>Delay interaction with Lazy CqlSession bean until first required
usage <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/39948">#39948</a></li>
<li>Add property spring.data.jdbc.dialect <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/39941">#39941</a></li>
<li>Make spring-test available to compile classpath of consumers of
spring-boot-test <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/39901">#39901</a></li>
<li>Exclude infrastructure beans from lazy initialization when
lazy-initialization=true <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/39831">#39831</a></li>
<li>Configure JpaBaseConfiguration with custom ManagedClassNameFilter <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/39813">#39813</a></li>
<li>Add property to ignore running Docker Compose services <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/39749">#39749</a></li>
<li>Add configuration property to disable long timers in Micrometer
Observations <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/39618">#39618</a></li>
<li>Upgrade Cassandra driver to 4.18.0 and change coordinates from
com.datastax.oss to org.apache.cassandra <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/39090">#39090</a></li>
<li>Add more gap between the orders of
CloudFoundryVcapEnvironmentPostProcessor and
ConfigDataEnvironmentPostProcessor <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38684">#38684</a></li>
<li>Add SNI support to embedded web server SSL auto-configuration <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/26022">#26022</a></li>
</ul>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li>Executable JAR application startup is slower after 3.2.0 when
Hibernate scanner is not disabled <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40381">#40381</a></li>
<li>NoClassDefFoundError can be thrown from LaunchedClassLoader when
threads are interrupted <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40379">#40379</a></li>
<li>BindValidationFailureAnalyzer uses wrong target <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40365">#40365</a></li>
<li>Log4j2LoggingSystem pollutes Log4j2's environment with a
SpringEnvironmentPropertySource that is never removed <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40327">#40327</a></li>
<li>When using Maven, configuring the spring-boot.excludes or
spring-boot-includes user properties causes the build to fail with
&quot;Cannot find default setter&quot; <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40324">#40324</a></li>
<li><code>@ServletComponentScan</code> does not register servlet
components in a mock web environment <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40322">#40322</a></li>
<li>Loading of custom deny-all filter can cause a StackOverflowError
when deploying to Tomcat with Log4j2 configured to use a single JVM-wide
logger context <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40313">#40313</a></li>
<li>Jetty support doesn't set virtual thread name <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40169">#40169</a></li>
<li>Maven uses 'start-class' when the parent POM is being used and
ignores 'spring-boot.run.main-class' <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40145">#40145</a></li>
<li>PropertiesLdapConnectionDetails should not be public <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/40081">#40081</a></li>
<li>spring.datasource.dbcp2.username and
spring.datasource.dbcp2.password are incorrectly marked as deprecated <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40076">#40076</a></li>
<li>spring-boot-dependencies should not manage
org.flywaydb:flyway-community-db-support as it is not released as part
of Flyway <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/40073">#40073</a></li>
<li>Spring Config does not use environment conversion service on
resolved properties <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/39944">#39944</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Producible's javadoc has the wrong link text for
<code>@WriteOperation</code> and <code>@DeleteOperation</code> <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40387">#40387</a></li>
<li>Add reference to OpenTelemetry Spring Boot starter <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40339">#40339</a></li>
<li>Refine Efficient Deployments section in the reference guide <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/40175">#40175</a></li>
<li>Clarify requirements for -parameters and constructor binding <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40164">#40164</a></li>
<li>Ensure Reference Guides breadcrumb in page headers is hyperlinked <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/40135">#40135</a></li>
<li>Document new tools mode <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40094">#40094</a></li>
<li>Add reference to Nostr Spring Boot Starter <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40080">#40080</a></li>
<li>Replace links to code with links to javadoc <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40065">#40065</a></li>
<li>Document CDS support <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40061">#40061</a></li>
<li>Document SBOM Support <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40059">#40059</a></li>
<li>Fix forward-headers-strategy documentation regarding cloud defaults
<a
href="https://redirect.github.com/spring-projects/spring-boot/pull/40054">#40054</a></li>
<li>Pull the whole &quot;Testing&quot; documentation section up to the
top level <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38361">#38361</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/a25e1ebe41bc02c5e7341ed1464d61c496cffe7c"><code>a25e1eb</code></a>
Release v3.3.0</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/ed0a3fd90845ebfa6a851c7c5d712a0ba0dcaa69"><code>ed0a3fd</code></a>
Update publish-to-sdkman job to make new candidates the default</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/42d6f2c7a85690a444c1555fea2d72f3576f6d0b"><code>42d6f2c</code></a>
Merge branch '3.2.x'</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/234e0fd1f395ed284cd8b4726c9b73d695c28b27"><code>234e0fd</code></a>
Stop mark 3.2.x as the default SDKman release</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/226b900babb25112e0ef0dcb02e2c06ce18564dd"><code>226b900</code></a>
Merge branch '3.2.x'</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/c857eb62d483865bc260ea1becab4bb456468772"><code>c857eb6</code></a>
Fix SDKman &quot;make default&quot; step</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/13e13f91c09f5012eb3bc61d39455ae5d4b43eff"><code>13e13f9</code></a>
Merge branch '3.2.x'</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/a5ee37c5262270a8d6a0e898a441f35677310d59"><code>a5ee37c</code></a>
Next development version (v3.2.7-SNAPSHOT)</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/dffdd6d67ca0f1b46cf2645439a3552fa6c5f5d2"><code>dffdd6d</code></a>
Explicitly set SDKman's make-default to false</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/86c206a849b746127be234ec3febd5eac5fc357e"><code>86c206a</code></a>
Merge branch '3.2.x'</li>
<li>Additional commits viewable in <a
href="https://github.com/spring-projects/spring-boot/compare/v3.2.5...v3.3.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.springframework.boot&package-manager=gradle&previous-version=3.2.5&new-version=3.3.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>